import type { NextPage } from 'next';
import Head from 'next/head';
import Header from 'sections/Header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Header transparentOnTop={false} />
      </main>
    </div>
  );
};

export default Home;
