import type { NextPage } from 'next';
import Head from 'next/head';
import AboutUs from 'sections/AboutUs/AboutUs';
import Banner from 'sections/Banner/Banner';
import FoodCategory from 'sections/FoodCategory/FoodCategory';
import Header from 'sections/Header/Header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-black-1">
        <Header />
        <Banner />
        <AboutUs />
        <FoodCategory />
      </main>
    </div>
  );
};

export default Home;
